#!/bin/sh /etc/rc.common
# Copyright (C) 2025 Teltonika
# SX1302 LoRa Packet Forwarder init script

START=90
STOP=10

USE_PROCD=1
PROG=/usr/bin/lora_pkt_fwd
CONF_DIR=/etc/lora

start_service() {
	# Reset the LoRa concentrator before starting
	/usr/sbin/reset_lgw.sh start

	procd_open_instance
	procd_set_param command $PROG
	procd_set_param respawn ${respawn_threshold:-3600} ${respawn_timeout:-5} ${respawn_retry:-5}
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_set_param pidfile /var/run/lora_pkt_fwd.pid
	procd_set_param file $CONF_DIR/global_conf.json
	procd_close_instance
}

stop_service() {
	# Reset the LoRa concentrator after stopping
	/usr/sbin/reset_lgw.sh stop
}

reload_service() {
	stop
	start
}
